BaseUri=http://localhost:3000/
DatabaseFilePath=jdbc:postgresql://coursinfo.vinci.be:5432/dbkawtar_dahman?user=kawtar_dahman
<<<<<<< HEAD
JWTSecret=Groupe06
DatabaseUser=kawtar_dahman
DatabasePassword=Groupe06
=======
DatabaseUser=kawtar_dahman
JWTSecret=Groupe06
>>>>>>> e72932560d3b7411c173a0c523f7189bc60001a6
