BaseUri=http://localhost:3000/
DatabaseFilePath=jdbc:postgresql://coursinfo.vinci.be:5432/dbguillaume_kennes?user=guillaume_kennes
DatabaseUser=guillaume_kennes
DatabasePassword=postgres
JWTSecret=Groupe06
