@baseUrl = http://localhost:3000




### Get all companies
GET {{baseUrl}}/companies/getEnterprises
Authorization: {{leleuxToken}}

### Get all companies for a specefic year
GET {{baseUrl}}/companies/getEnterprises/2023-2024
Authorization: {{leleuxToken}}


### Get all companies for a specefic year
GET {{baseUrl}}/companies/getEnterprises/2023
Authorization: {{leleuxToken}}