@baseUrl = http://localhost:3000

### Insert a new Company
POST {{baseUrl}}/company/add
Content-Type: application/json

{
  "tradeName": "Niboo",
  "designation": "boobi",
  "address": "ch43",
  "city": "Bruxelles",
  "meansOfCommunication": "04 504974833"
}


### Get number of students taken by a company
GET {{baseUrl}}/companies/numberOfStudentsTaken/1
Authorization: {{leleuxToken}}

### Get number of students taken by a company
GET {{baseUrl}}/companies/numberOfStudentsTaken/2
Authorization: {{leleuxToken}}

### Get number of students taken by a company
GET {{baseUrl}}/companies/numberOfStudentsTaken/3
Authorization: {{leleuxToken}}

### Get number of students taken by a company
GET {{baseUrl}}/companies/numberOfStudentsTaken/4
Authorization: {{leleuxToken}}

### ici c est les noms de CompanyImpl

### requete blackList
POST {{baseUrl}}/companies/blacklist/3
Content-Type: application/json

{

}