@baseUrl = http://localhost:3000

### Insert a new Company
POST {{baseUrl}}/company/add
Content-Type: application/json

{
  "tradeName": "Niboo",
  "designation": "boobi",
  "address": "ch43",
  "city": "Bruxelles",
  "meansOfCommunication": "04 504974833"
}

### ici c est les noms de CompanyImpl

### requete blackList
POST {{baseUrl}}/companies/blacklist/3
Content-Type: application/json

{

}