@baseurl = http://localhost:3000

### requete meetCompany
POST {{baseurl}}/contacts/meet/9
Content-Type: application/json

{
  "meetLocation": "enterprise"
}

### requete stopFollowing
POST {{baseurl}}/contacts/stop/9
Content-Type: application/json

{

}

### requete companyRefusedInternship
POST {{baseurl}}/contacts/companyrefused/9
Content-Type: application/json

{
  "reasonRefusal": "On n'a plus de place"
}

