@baseUrl = http://localhost:3000

### Login a user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"Caroline.line@student.vinci.be",
  "password":"mdpuser.1"
}
> {%
  client.global.set("carolineToken", response.body.token);
%}

### Login another user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"raphael.baroni@vinci.be" ,
  "password": "Prof24,z"
}
> {%
  client.global.set("baroniToken", response.body.token);
%}

### Login another user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"laurent.leleux@vinci.be" ,
  "password": "Prof24,z"
}
> {%
  client.global.set("leleuxToken", response.body.token);
%}


### Login another user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"annouck.lancaster@vinci.be",
  "password": "Admin;10."
}
> {%
  client.global.set("annouckToken", response.body.token);
%}

### Get an user by it's id
GET {{baseUrl}}/users/7

### Get all users with a teacher token
GET {{baseUrl}}/users
Authorization: {{baroniToken}}

### Get all users with a student token
GET {{baseUrl}}/users/getAllUsers
Authorization: {{carolineToken}}

### Get all users with a teacher token
GET {{baseUrl}}/users/getAllUsers
Authorization: {{leleuxToken}}

### Get all users with an admin token
GET {{baseUrl}}/users/getAllUsers
Authorization: {{annouckToken}}

### Register an user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "ryuyuer@student.vinci.be",
  "password": "mdp1",
  "lastName": "test",
  "firstName": "TEST",
  "phoneNumber": "0546546545",
  "role": "Student",
  "versionNumber": 1
}
